### ISSUE TITLE
关于linux lab

### ISSUE THREAD

**Issue by Deniffer** [Inch-Z/OS#1]
烦请问能借用linux lab账号嘛？

![image](https://user-images.githubusercontent.com/46983419/98459980-e1370a80-21da-11eb-93d5-4f5de6849b0b.png)

**Comment by Inch-Z** [comment]
你是哪位



---原始邮件---
发件人: "Deniffer"<notifications@github.com&gt;
发送时间: 2020年11月8日(周日) 下午3:56
收件人: "Inch-Z/OS"<OS@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Inch-Z/OS] 关于linux lab (#1)




 
烦请问能借用linux lab账号嘛？

**Comment by Deniffer** [comment]
> 你是哪位
> […](#)
> ---原始邮件--- 发件人: "Deniffer"<notifications@github.com&gt; 发送时间: 2020年11月8日(周日) 下午3:56 收件人: "Inch-Z/OS"<OS@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Inch-Z/OS] 关于linux lab (#1) 烦请问能借用linux lab账号嘛？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

一名某不知名大学生看到你的lab note 想复现一遍

**Comment by Inch-Z** [comment]
这个要服务器的，学校作业😂



---原始邮件---
发件人: "Deniffer"<notifications@github.com&gt;
发送时间: 2020年11月8日(周日) 下午4:01
收件人: "Inch-Z/OS"<OS@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Inch.Zhang"<1666161794@qq.com&gt;;
主题: Re: [Inch-Z/OS] 关于linux lab (#1)




  
你是哪位
 …
 ---原始邮件--- 发件人: "Deniffer"<notifications@github.com&gt; 发送时间: 2020年11月8日(周日) 下午3:56 收件人: "Inch-Z/OS"<OS@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Inch-Z/OS] 关于linux lab (#1) 烦请问能借用linux lab账号嘛？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
一名某不知名大学生看到你的lab note 想复现一遍

**Comment by Deniffer** [comment]
> 这个要服务器的，学校作业😂
> […](#)
> ---原始邮件--- 发件人: "Deniffer"<notifications@github.com&gt; 发送时间: 2020年11月8日(周日) 下午4:01 收件人: "Inch-Z/OS"<OS@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Inch.Zhang"<1666161794@qq.com&gt;; 主题: Re: [Inch-Z/OS] 关于linux lab (#1) 你是哪位 … ---原始邮件--- 发件人: "Deniffer"<notifications@github.com&gt; 发送时间: 2020年11月8日(周日) 下午3:56 收件人: "Inch-Z/OS"<OS@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Inch-Z/OS] 关于linux lab (#1) 烦请问能借用linux lab账号嘛？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 一名某不知名大学生看到你的lab note 想复现一遍 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是校内服务器才能用吗？还是随便一台linux操作系统

**Comment by Inch-Z** [comment]
> > 这个要服务器的，学校作业😂
> > […](#)
> > ---原始邮件--- 发件人: "Deniffer"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年11月8日(周日) 下午4:01 收件人: "Inch-Z/OS"<[OS@noreply.github.com](mailto:OS@noreply.github.com)>; 抄送: "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>;"Inch.Zhang"<[1666161794@qq.com](mailto:1666161794@qq.com)>; 主题: Re: [Inch-Z/OS] 关于linux lab (#1) 你是哪位 … ---原始邮件--- 发件人: "Deniffer"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年11月8日(周日) 下午3:56 收件人: "Inch-Z/OS"<[OS@noreply.github.com](mailto:OS@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [Inch-Z/OS] 关于linux lab (#1) 烦请问能借用linux lab账号嘛？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 一名某不知名大学生看到你的lab note 想复现一遍 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 是校内服务器才能用吗？还是随便一台linux操作系统
我们是校内服务器才能用的，可以尝试直接安装linux系统再虚拟机内运行。
